apiVersion: apps/v1
kind: Deployment
metadata:
  name: ytclfr-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ytclfr-api
  template:
    metadata:
      labels:
        app: ytclfr-api
    spec:
      containers:
        - name: api
          image: ytclfr/api:latest
