apiVersion: apps/v1
kind: Deployment
metadata:
  name: ytclfr-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ytclfr-worker
  template:
    metadata:
      labels:
        app: ytclfr-worker
    spec:
      containers:
        - name: worker
          image: ytclfr/worker:latest
